# Generated by Django 3.0.4 on 2020-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('case', models.IntegerField()),
                ('death', models.IntegerField()),
                ('recover', models.IntegerField()),
            ],
        ),
    ]
